### ISSUE TITLE
Compute stats - data for paper

### ISSUE THREAD

**Issue by mwhicks1** [correctcomputation/analyse-conv#6]
We want to tabulate the changes / work at various stages. I propose we compute the following:

- Original program (`orig`) --> Manual port, reverted (`revert`): Count the lines changed (added/removed)
- `revert` --> manual port (`manual`): Checked pointer statistics & lines changed
- 3C applied to `revert`: Checked pointer statistics & lines changed
- 3C applied to `orig`: Checked pointer statistics & lines changed

For "Checked pointer statistics" I mean the result of `3c -dump-stats`, but enhanced to include casts. Here's the table we can generate, filling out the entry for `yacr2`. 

```
Program | Ver      | Lines refc. | Lines annot. | # ptr | #ntarr | #arr | #wild | #bounds | #casts 
--------------------------------------------------------------------------------------------------
yacr2   | manual   | 168 (6.5%)  | 290 (11%)    | 15    | 5      | 135  | 1     | ?       | ?
        | revert   | n/a         | 253 (9.6%)   | 54    | 4      | 93   | 5     | ?       | ?
        | orig     | n/a         | 245 (9.4%)   | 53    | 0      | 93   | 10    | ?       | ?
anagram | manual   | ...
```
The first row comes from bullets 1 and 2; the second and third come from bullets 3 and 4, respectively.

**To-do list**

- [x] Change `src/create-stats.sh` to compute the refactoring statistics, per program
- [x] Change `src/combine-stats.sh` to combine statistics within Olden, Ptrdist
- [x] Fix `3c -dump-stats` to properly compute bounds information
- [x] Fix `3c -dump-stats` to count added casts
- [x] Update repo to call `3c` to compute pointer count information. Probably want a new script in `src` to do this; the aggregate JSON results are saved (other files generated are discarded).
- [x] Update `3c -dump-stats` to compute missing information ([this issue](https://github.com/correctcomputation/checkedc-clang/issues/565))
- [x] Write script to compute the above table as `.tex`, from the gathered data files

Details on these tasks below.

### Lines refactored

For the lines-refactored count, we can do this (from the `analyse-conv/src/Ptrdist/yacr2` directory):
```
> diff -w orig revert | diffstat -s
 12 files changed, 168 insertions(+), 139 deletions(-)
```
where the total lines are
```
> sloccount orig
... (lists the 14 files) ...
Totals grouped by language (dominant language first):
ansic:         2597 (100.00%)
```
Assuming every inserted line matches a deleted one, we determined `MAX(#insert,#delete)` to be "lines changed," giving us 168, or 6.5% of the total lines (168/2597 * 100).

For the lines-annotated counts, we do
- `diff -w revert manual | diffstat -s` relative to `sloccount revert`
- `diff -w revert 3c-revert | diffstat -s` relative to `sloccount revert`
- `diff -w orig 3c-revert | diffstat -s` relative to `sloccount orig`

Currently, the line-diff computation is in https://github.com/correctcomputation/analyse-conv/blob/main/src/create-stats.sh#L25; it computes more detailed, per-file statistics, but I don't think we need them. We will need to change the format of this file, and add to it the line counts from sloccount.

### Pointer statistics

We compute pointer statistics on three versions. We run `3c` as already demanded herein (same flags, targets) for `orig` and `3c-orig`, but with `-dump-stats`. But we also run it on `manual` (with the same flags as the other targets). For example, for `manual` the command line could be
```
> 3c -alltypes -base-dir=manual -output-dir=/tmp -extra-arg-before=-I.. -extra-arg-before=-DTODD -dump-stats manual/assign.c manual/hcg.c manual/maze.c manual/vcg.c manual/channel.c manual/main.c manual/option.c
...
Summary
TotalConstraints|TotalPtrs|TotalNTArr|TotalArr|TotalWild
156|15|5|135|1
NumPointersNeedBounds:59,
NumNTNoBounds:0,
Details:
Invalid:58
,BoundsFound:
Array Bounds Inference Stats:
NamePrefixMatch:0
AllocatorMatch:0
VariableNameMatch:0
NeighbourParamMatch:0
DataflowMatch:0
Declared:1
```
The above output is stored in JSON format in the file `TotalConstraintStats.json.aggregate.json`. Some other JSON files are generated, which we can discard. 

We'll want to extend `-dump-stats` to include added Checked C casts --- `_Assume_bounds_cast` and `Dynamic_cast` (are there others?). It also seems like the computed bounds information is off; we want to count things beyond just `count(c)` and `byte_count(b)` to also include `bounds(p,q)`. I think we can ignore added `_Unchecked` annotations, since this determination seems more subjective, and it's hard to match per-function annotations (what `-addcr` does) to the whole-function `#pragma`. See https://github.com/correctcomputation/checkedc-clang/issues/565
